version: '3.8'

services:
  app:
    build: .
    container_name: todo_app
    ports:
     - "3001:3000"
    environment:
      - DB_HOST=db 
      - DB_USER=root
      - DB_PASSWORD=1234
      - DB_NAME=todo_db
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: todo_db
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: todo_db
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:




